#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
SRC_DIR="${SCRIPT_DIR}/scripts"
BIN_DIR="${HOME}/.local/bin"

if [ ! -d "$SRC_DIR" ]; then
  echo "错误: 找不到脚本目录: $SRC_DIR" >&2
  exit 1
fi

command_name_for() {
  local base="$1"

  case "$base" in
    *.sh) base="${base%.sh}" ;;
    *.py) base="${base%.py}" ;;
    *.js) base="${base%.js}" ;;
    *.pl) base="${base%.pl}" ;;
    *.rb) base="${base%.rb}" ;;
  esac

  printf '%s\n' "${base//_/-}"
}

mkdir -p "$BIN_DIR"

install_wrapper() {
  local command_name="$1"
  local src="$2"
  local target="${BIN_DIR}/${command_name}"

  if [ -d "$target" ] && [ ! -L "$target" ]; then
    echo "错误: 目标路径是目录，无法安装: $target" >&2
    exit 1
  fi

  {
    printf '%s\n' '#!/usr/bin/env bash'
    printf '%s\n' '# generated by my-tools/install.sh'
    printf 'exec %q "$@"\n' "$src"
  } > "$target"

  chmod +x "$target"
  echo "已安装: $target -> $src"
}

install_aliases() {
  local command_name="$1"
  local src="$2"

  case "$command_name" in
    wait-and-run)
      install_wrapper "war" "$src"
      ;;
  esac
}

installed_any=0
shopt -s nullglob

for src in "$SRC_DIR"/*; do
  [ -f "$src" ] || continue
  [ -x "$src" ] || continue

  command_name="$(command_name_for "$(basename "$src")")"
  install_wrapper "$command_name" "$src"
  install_aliases "$command_name" "$src"
  installed_any=1
done

if [ "$installed_any" -eq 0 ]; then
  echo "错误: 没有发现可安装的可执行脚本" >&2
  exit 1
fi

case ":$PATH:" in
  *":$BIN_DIR:"*)
    ;;
  *)
    echo "提示: 你的 PATH 里还没有 $BIN_DIR"
    echo "可以加入：export PATH=\"\$HOME/.local/bin:\$PATH\""
    ;;
esac
